// server/models/timelog.model.js (CORRIGÉ - champs auto-déconnexion ajoutés)
const mongoose = require('mongoose');

const locationSchema = new mongoose.Schema({
  name: String,
  coordinates: {
    latitude: Number,
    longitude: Number
  },
  ipAddress: String  // Stocker l'IP pour l'audit
});

const timelogSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  startTime: {
    type: Date,
    required: true,
    default: Date.now
  },
  endTime: {
    type: Date,
    default: null
  },
  status: {
    type: String,
    enum: ['active', 'completed'],
    default: 'active'
  },
  // NOUVEAU: Type de pointage pour les drivers
  type: {
    type: String,
    enum: ['start_service', 'start_break', 'end_break', 'end_service', 'general'],
    default: 'general' // Pour compatibilité avec les anciens enregistrements
  },
  // NOUVEAU: Indique si le pointage a été créé automatiquement
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  // NOUVEAU: Indique si l'utilisateur a été déconnecté automatiquement
  isAutoDisconnected: {
    type: Boolean,
    default: false
  },
  // NOUVEAU: Raison de la déconnexion automatique
  autoDisconnectReason: {
    type: String,
    default: undefined
  },
  // CORRIGÉ: Raison de la création automatique - accepte null/undefined
  autoGenerationReason: {
    type: String,
    enum: {
      values: ['missing_break', 'missing_break_end', 'missing_service_end'],
      message: '{VALUE} is not a valid auto generation reason'
    },
    required: false,
    default: undefined // Utiliser undefined au lieu de null
  },
  location: {
    startLocation: locationSchema,
    endLocation: locationSchema
  },
  notes: String
}, {
  timestamps: true
});

// Index pour rechercher efficacement les entrées de pointage par utilisateur et statut
timelogSchema.index({ userId: 1, status: 1 });
// Nouvel index pour les types de pointage
timelogSchema.index({ userId: 1, type: 1, createdAt: -1 });
// Index pour l'auto-déconnexion
timelogSchema.index({ status: 1, isAutoDisconnected: 1 });

module.exports = mongoose.model('TimeLog', timelogSchema);